import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Transition from "./components/Transition";
import "./globals.css";
import ThemeSwitch from "@/components/Switch/Theme/Index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      // className={`${geistSans.variable} ${geistMono.variable} bg-[#f3f3fb] dark:bg-transparent`}
      >
        <div className="fixed top-4 right-4">
          <ThemeSwitch />
        </div>

        <Transition>
          {children}
        </Transition>
      </body>
    </html>
  );
}
